# *** This Dockefile is generated by KloverCloud. You can modify it based on your application requirements *** #

FROM container-registry.console.klovercloud.com/klovercloud/golang:1.14 as builder

WORKDIR /app



COPY . .

RUN go build -o /app/bin/CRUD-application .

FROM container-registry.console.klovercloud.com/klovercloud/golang:1.14

RUN useradd -ms /bin/bash klovercloud

WORKDIR /home/klovercloud

COPY --from=builder /app/bin .


EXPOSE 8080

EXPOSE 8081


USER klovercloud
# Run the executable
CMD ["./CRUD-application"]
